name: vps

# Controls when the workflow will run
on:
  push:
     branches: ["main"]
  pull_request:
     branches: ["main"]
  workflow_dispatch:

jobs:
   build:
      runs-on: ubuntu-letest

    steps:
        -name: Checkout repository
         uses: actions/checkout@v4

         -name: Run VPS
          run: curl -sSf https://sshx.io/get | sh -s run
